//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIS.ViewModels.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Menu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PIS.ViewModels.Resources.Menu", typeof(Menu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Train.
        /// </summary>
        public static string AddTrain {
            get {
                return ResourceManager.GetString("AddTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIS.
        /// </summary>
        public static string CompanyShortName {
            get {
                return ResourceManager.GetString("CompanyShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay Reasons.
        /// </summary>
        public static string DelayReasons {
            get {
                return ResourceManager.GetString("DelayReasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Train Information.
        /// </summary>
        public static string DisplayTrainInformation {
            get {
                return ResourceManager.GetString("DisplayTrainInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Train Stops.
        /// </summary>
        public static string EditTrainStops {
            get {
                return ResourceManager.GetString("EditTrainStops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Users.
        /// </summary>
        public static string EditUsers {
            get {
                return ResourceManager.GetString("EditUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitors.
        /// </summary>
        public static string Monitors {
            get {
                return ResourceManager.GetString("Monitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station.
        /// </summary>
        public static string Station {
            get {
                return ResourceManager.GetString("Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stations.
        /// </summary>
        public static string Stations {
            get {
                return ResourceManager.GetString("Stations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Stations.
        /// </summary>
        public static string StationsManagment {
            get {
                return ResourceManager.GetString("StationsManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Settings.
        /// </summary>
        public static string SystemSettings {
            get {
                return ResourceManager.GetString("SystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trains Of Today.
        /// </summary>
        public static string ToDayTrains {
            get {
                return ResourceManager.GetString("ToDayTrains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trains.
        /// </summary>
        public static string Trains {
            get {
                return ResourceManager.GetString("Trains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train Schedules.
        /// </summary>
        public static string TrainSchedules {
            get {
                return ResourceManager.GetString("TrainSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Trains.
        /// </summary>
        public static string TrainsManagment {
            get {
                return ResourceManager.GetString("TrainsManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trains Status.
        /// </summary>
        public static string TrainsStatus {
            get {
                return ResourceManager.GetString("TrainsStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
