//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIS.ViewModels.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Stations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Stations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PIS.ViewModels.Resources.Stations", typeof(Stations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string ConfirmDeleteStation {
            get {
                return ResourceManager.GetString("ConfirmDeleteStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Station.
        /// </summary>
        public static string DeleteStation {
            get {
                return ResourceManager.GetString("DeleteStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Station Details.
        /// </summary>
        public static string EditStationViewModel {
            get {
                return ResourceManager.GetString("EditStationViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified Date.
        /// </summary>
        public static string LastModified {
            get {
                return ResourceManager.GetString("LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Station.
        /// </summary>
        public static string LblAddNewStation {
            get {
                return ResourceManager.GetString("LblAddNewStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Station, are you sure?.
        /// </summary>
        public static string msgConfirmSwitchStation {
            get {
                return ResourceManager.GetString("msgConfirmSwitchStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station arabic name is required.
        /// </summary>
        public static string RequiredStationNameErrorMsg {
            get {
                return ResourceManager.GetString("RequiredStationNameErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station Code.
        /// </summary>
        public static string StationCode {
            get {
                return ResourceManager.GetString("StationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station Arabic Name.
        /// </summary>
        public static string StationNameAr {
            get {
                return ResourceManager.GetString("StationNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station English Name.
        /// </summary>
        public static string StationNameEn {
            get {
                return ResourceManager.GetString("StationNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Station.
        /// </summary>
        public static string SwitchStation {
            get {
                return ResourceManager.GetString("SwitchStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Stations.
        /// </summary>
        public static string ViewStationsLable {
            get {
                return ResourceManager.GetString("ViewStationsLable", resourceCulture);
            }
        }
    }
}
