//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIS.ViewModels.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Train {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Train() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PIS.ViewModels.Resources.Train", typeof(Train).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Schedule.
        /// </summary>
        public static string BtnEditSchedule {
            get {
                return ResourceManager.GetString("BtnEditSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Train Schedule.
        /// </summary>
        public static string EditTrainSchedule {
            get {
                return ResourceManager.GetString("EditTrainSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train Arabic Status.
        /// </summary>
        public static string LabelArabicStatusName {
            get {
                return ResourceManager.GetString("LabelArabicStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train English Status.
        /// </summary>
        public static string LabelEnglishStatusName {
            get {
                return ResourceManager.GetString("LabelEnglishStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete selected train, are you sure?.
        /// </summary>
        public static string MsgDeleteTrain {
            get {
                return ResourceManager.GetString("MsgDeleteTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orignal Arrival Time.
        /// </summary>
        public static string OrignalArrivalTime {
            get {
                return ResourceManager.GetString("OrignalArrivalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orignal Depatrute Time.
        /// </summary>
        public static string OrignalDepatruteTime {
            get {
                return ResourceManager.GetString("OrignalDepatruteTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train Arabic Status Name.
        /// </summary>
        public static string RequiredArabicStatusName {
            get {
                return ResourceManager.GetString("RequiredArabicStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival time is required.
        /// </summary>
        public static string RequiredArrivalTime {
            get {
                return ResourceManager.GetString("RequiredArrivalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure time is required.
        /// </summary>
        public static string RequiredDepartureTime {
            get {
                return ResourceManager.GetString("RequiredDepartureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train number is required.
        /// </summary>
        public static string RequiredTrainNumber {
            get {
                return ResourceManager.GetString("RequiredTrainNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train Status is required.
        /// </summary>
        public static string RequiredTrainStatus {
            get {
                return ResourceManager.GetString("RequiredTrainStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Status.
        /// </summary>
        public static string SelectStatus {
            get {
                return ResourceManager.GetString("SelectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Train Trips.
        /// </summary>
        public static string ShowTrainTrips {
            get {
                return ResourceManager.GetString("ShowTrainTrips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train Classes.
        /// </summary>
        public static string TrainClasses {
            get {
                return ResourceManager.GetString("TrainClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train Days.
        /// </summary>
        public static string TrainDays {
            get {
                return ResourceManager.GetString("TrainDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train Status.
        /// </summary>
        public static string TrainStatus {
            get {
                return ResourceManager.GetString("TrainStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train Type.
        /// </summary>
        public static string TrainType {
            get {
                return ResourceManager.GetString("TrainType", resourceCulture);
            }
        }
    }
}
