//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIS.ViewModels.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TrainTrip {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TrainTrip() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PIS.ViewModels.Resources.TrainTrip", typeof(TrainTrip).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journy.
        /// </summary>
        public static string A_Journy {
            get {
                return ResourceManager.GetString("A_Journy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival Time.
        /// </summary>
        public static string ArrivalTime {
            get {
                return ResourceManager.GetString("ArrivalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival Time Required.
        /// </summary>
        public static string ArrivalTimeRequired {
            get {
                return ResourceManager.GetString("ArrivalTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class B.
        /// </summary>
        public static string Class0AName {
            get {
                return ResourceManager.GetString("Class0AName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class A.
        /// </summary>
        public static string Class1AName {
            get {
                return ResourceManager.GetString("Class1AName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay Reason.
        /// </summary>
        public static string DelayReason {
            get {
                return ResourceManager.GetString("DelayReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay Status.
        /// </summary>
        public static string DelayStatus {
            get {
                return ResourceManager.GetString("DelayStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Train.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Delete.
        /// </summary>
        public static string DeleteTrip {
            get {
                return ResourceManager.GetString("DeleteTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure Time.
        /// </summary>
        public static string DepartureTime {
            get {
                return ResourceManager.GetString("DepartureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure Time Required.
        /// </summary>
        public static string DepartureTimeRequired {
            get {
                return ResourceManager.GetString("DepartureTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Train Details.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Edit.
        /// </summary>
        public static string EditTrip {
            get {
                return ResourceManager.GetString("EditTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform Number.
        /// </summary>
        public static string EndPlatformNumber {
            get {
                return ResourceManager.GetString("EndPlatformNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Station.
        /// </summary>
        public static string EndStation {
            get {
                return ResourceManager.GetString("EndStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Station Required.
        /// </summary>
        public static string EndStationRequired {
            get {
                return ResourceManager.GetString("EndStationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Station Code.
        /// </summary>
        public static string FinalStationCode {
            get {
                return ResourceManager.GetString("FinalStationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Station.
        /// </summary>
        public static string LblAddNew {
            get {
                return ResourceManager.GetString("LblAddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Trains.
        /// </summary>
        public static string NumberOfTrains {
            get {
                return ResourceManager.GetString("NumberOfTrains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plateform.
        /// </summary>
        public static string PlateformNo {
            get {
                return ResourceManager.GetString("PlateformNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform Number.
        /// </summary>
        public static string PlatformNumber {
            get {
                return ResourceManager.GetString("PlatformNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform Number Required.
        /// </summary>
        public static string PlatformNumberRequired {
            get {
                return ResourceManager.GetString("PlatformNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string Reasons {
            get {
                return ResourceManager.GetString("Reasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Details.
        /// </summary>
        public static string ShowDetails {
            get {
                return ResourceManager.GetString("ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform Number.
        /// </summary>
        public static string StartPlatformNumber {
            get {
                return ResourceManager.GetString("StartPlatformNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Station.
        /// </summary>
        public static string StartStation {
            get {
                return ResourceManager.GetString("StartStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Station Code.
        /// </summary>
        public static string StartStationCode {
            get {
                return ResourceManager.GetString("StartStationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Station Required.
        /// </summary>
        public static string StartStationRequired {
            get {
                return ResourceManager.GetString("StartStationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station Code.
        /// </summary>
        public static string StationCode {
            get {
                return ResourceManager.GetString("StationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station Name.
        /// </summary>
        public static string StationName {
            get {
                return ResourceManager.GetString("StationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station Required.
        /// </summary>
        public static string StationRequired {
            get {
                return ResourceManager.GetString("StationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Trains.
        /// </summary>
        public static string TainsNumber {
            get {
                return ResourceManager.GetString("TainsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time For Trains.
        /// </summary>
        public static string TimeForTrains {
            get {
                return ResourceManager.GetString("TimeForTrains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train.
        /// </summary>
        public static string Train {
            get {
                return ResourceManager.GetString("Train", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Class Name.
        /// </summary>
        public static string TrainArabicClass {
            get {
                return ResourceManager.GetString("TrainArabicClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Englisg Class Name.
        /// </summary>
        public static string TrainEnglisgClass {
            get {
                return ResourceManager.GetString("TrainEnglisgClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train Number.
        /// </summary>
        public static string TrainNo {
            get {
                return ResourceManager.GetString("TrainNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train Number Exists Before.
        /// </summary>
        public static string TrainNoExistBefore {
            get {
                return ResourceManager.GetString("TrainNoExistBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station arabic name is required.
        /// </summary>
        public static string TrainNoRequired {
            get {
                return ResourceManager.GetString("TrainNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train Status.
        /// </summary>
        public static string TrainStatus {
            get {
                return ResourceManager.GetString("TrainStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train Type.
        /// </summary>
        public static string TrainTypeAName {
            get {
                return ResourceManager.GetString("TrainTypeAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Details.
        /// </summary>
        public static string TripDetails {
            get {
                return ResourceManager.GetString("TripDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Trains.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withou Platform.
        /// </summary>
        public static string WithoutPlatform {
            get {
                return ResourceManager.GetString("WithoutPlatform", resourceCulture);
            }
        }
    }
}
